FROM node:24-alpine

RUN apk add --no-cache bash curl libc6-compat
USER node

WORKDIR /app

COPY --chown=node:node ./packages/server/package.json .
COPY --chown=node:node ./packages/server/package-lock.json .
RUN npm install

COPY --chown=node:node ./packages/server .
COPY --chown=node:node .env .

CMD ["npm", "run", "dev"]