# builder stage
FROM node:24-alpine AS builder

WORKDIR /app

COPY --chown=node:node ./packages/server/package*.json ./
RUN npm ci
COPY --chown=node:node ./packages/server/tsconfig.json ./
COPY --chown=node:node ./packages/server/src ./src
RUN npm run build

# production stage
FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --chown=node:node ./packages/server/package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3000

CMD ["node", "dist/index.js"]