FROM node:24-alpine

USER node

WORKDIR /app

COPY --chown=node:node ./packages/client/package.json .
COPY --chown=node:node ./packages/client/package-lock.json .
RUN npm install

COPY --chown=node:node ./packages/client .

CMD [ "npm", "run", "dev" ]
