# builder stage
FROM node:24-alpine AS builder

WORKDIR /app

COPY --chown=node:node ./packages/client/package*.json ./
RUN npm ci
COPY --chown=node:node ./packages/client .
RUN npm run build

# production stage
FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./docker/client/nginx/nginx.conf /etc/nginx/conf.d/default.conf